version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8.7

    steps:
      - checkout

      - restore_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install node dependencies
          command: |
            if [ ! -d ./node_modules ]; then
              yarn --pure-lockfile
            fi
      - save_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:8.7-browsers
        environment:
          JOBS: 2

    steps:
      - checkout
      - restore_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: npx ember test

workflows:
  version: 2
  just-test:
    jobs:
      - install
      - test:
          requires:
            - install


